###############################################################################
# (C) Copyright IBM Corp. 2019, 2021
#
# SPDX-License-Identifier: Apache-2.0
###############################################################################     

################################################################################################################
language: java

# Setup the distribution with git-lfs addon
# packages are installed in before_install 
# details on image https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-images
dist: bionic

jdk:
- openjdk11

# Matrix build (just incase we choose)
matrix: 
  fast_finish: true

# GIT Settings: 
branches:
  except:
  - gh-pages

# Make sure we are all up to date
before_install:
  - sudo apt-get update || true
  - sudo apt-get install git-lfs 

# Build and Release for Git Tag
script: 
  - |
    if [[ "${TRAVIS_EVENT_TYPE}" == "push" && "${TRAVIS_TAG}" != "" ]]
    then 
      echo "Not Used"
    fi

notifications:
  email:
    recipients: 
      - pbastide@us.ibm.com, lmsurpre@us.ibm.com
    on_success: never # default: change
    on_failure: always # default: always  

# EOF