name: Build and Release

on:
  push:
    tags:
      - '*.*'
    paths-ignore:
    - 'docs/**'
    - '.github/site.yml'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk11' ]
      fail-fast: false
    steps:
    - name: Setup Graphviz environment
      uses: kamiazya/setup-graphviz@v1
    - name: Grab the Master Branch
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        fetch-depth: 1
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build and Release Tags
      env:
        BASE: origin/${{ github['base_ref'] }}
        GITHUB_TOKEN: ${{ secrets.DOCS_SITE_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        CI: true
        JAVA_HOME: /opt/hostedtoolcache/AdoptOpenJDK/1.0.0-releases-${{ matrix.java }}-hotspot-normal-latest/x64/
      run: |
        bash build/release/bootstrap-env.sh
        # Only output this if you are debugging... cat ./build/release/bootstrap.env
        . ./build/release/bootstrap.env
        env
        bash build/release/version.sh
        bash build/release/clean.sh
        bash build/release/build.sh